taskname: '+ Student: MobileNetv1-1.0; Teacher: ResNet-101'
common:
  run_label: "train"
  log_freq: 500
  auto_resume: true
  mixed_precision: true
  channels_last: true
dataset:
  root_train: "/mnt/imagenet/training"
  root_val: "/mnt/imagenet/validation"
  name: "imagenet"
  category: "classification"
  train_batch_size0: 128 # effective batch size is 512 (128 * 4 GPUs)
  val_batch_size0: 100
  eval_batch_size0: 100
  workers: -1
  persistent_workers: true
  pin_memory: true
image_augmentation:
  # training transforms
  random_resized_crop:
    enable: true
    interpolation: "bilinear"
  random_horizontal_flip:
    enable: true
  # validation transforms
  resize:
    enable: true
    size: 232 # shorter size is 232
    interpolation: "bilinear"
  center_crop:
    enable: true
    size: 224
sampler:
  name: "variable_batch_sampler"
  vbs:
    crop_size_width: 224
    crop_size_height: 224
    max_n_scales: 5
    min_crop_size_width: 128
    max_crop_size_width: 320
    min_crop_size_height: 128
    max_crop_size_height: 320
    check_scale: 32
loss:
  category: "distillation"
  distillation:
    name: "cls_kl_div_loss"
    label_smoothing: 0.1
    cls_kl_div_loss:
      mode: "soft"
optim:
  name: "sgd"
  weight_decay: 4.e-5
  no_decay_bn_filter_bias: true
  sgd:
    momentum: 0.9
    nesterov: true
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 300
  warmup_iterations: 7500
  warmup_init_lr: 0.05
  cosine:
    max_lr: 0.4
    min_lr: 2.e-4
teacher:
  model:
    classification:
      name: "resnet"
      # PATH TO PRETRAINED TEACHER MODEL
      pretrained: "https://docs-assets.developer.apple.com/ml-research/models/cvnets-v2/classification/advanced/resnet-101-adv.pt"
      activation:
        name: "relu"
      resnet:
        depth: 101
    normalization:
      name: "batch_norm"
      momentum: 0.1
    activation:
      name: "relu"
      inplace: true
    layer:
      global_pool: "mean"
      conv_init: "kaiming_normal"
      linear_init: "normal"
model:
  classification:
    name: "mobilenetv1"
    activation:
      name: "relu"
    mobilenetv1:
      width_multiplier: 1.0
  normalization:
    name: "batch_norm"
    momentum: 0.1
  activation:
    name: "relu"
    inplace: false
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "normal"
ema:
  enable: true
  momentum: 0.0005
stats:
  val: [ "loss", "top1", "top5" ]
  train: ["loss"]
  checkpoint_metric: "top1"
  checkpoint_metric_max: true